[project]
name = "qompy"
version = "0.0.1"
authors = [
    { name = "Arvin Kushwaha", email = "arvin.singh.kushwaha@gmail.com" },
]
description = "A nice quantum computing simulation library."
readme = "README.md"
dependencies = [
    "numpy ~= 1.24.2",
    "scipy ~= 1.10.1"
]
